spring:
  application:
    name: app-red-social
  datasource:
    url: jdbc:postgresql://localhost/db-chat
    username: usr-chat
    password: qk07Pv2x6Zy077xUzAT5
  jpa:
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /api/redsocial
  port: 8080