spring:
  application:
    name: app-red-social
  datasource:
    url: jdbc:mysql://localhost:3434/redsocial
    username: usrredsocial
    password: KK2RsMdLiJbwDds644r3
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /api/redsocial
  port: 8080